spring:
  application:
    name: election-express
  datasource:
    url: jdbc:postgresql://localhost:5432/election_express_database
    username: postgres
    password: 55412678910
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  mail:
    default: gmail
    gmail:
      host: smtp.gmail.com
      port: 587
      username: orlinivanov69@gmail.com
      password: otda vttq okbw ycvu
      properties:
        mail.smtp.auth: true
        mail.smtp.starttls.enable: true
        mail.smtp.connectiontimeout: 5000
        mail.smtp.timeout: 5000
        mail.smtp.writetimeout: 5000
    abv:
      host: smtp.abv.bg
      port: 465
      username: orlin11111@abv.bg
      password: Por55412678910
      properties:
        mail.smtp.auth: true
        mail.smtp.ssl.enable: true
        mail.smtp.connectiontimeout: 5000
        mail.smtp.timeout: 5000
        mail.smtp.writetimeout: 5000